/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdityaRouteImport } from './routes/aditya'
import { Route as IndexRouteImport } from './routes/index'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdityaRoute = AdityaRouteImport.update({
  id: '/aditya',
  path: '/aditya',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aditya': typeof AdityaRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aditya': typeof AdityaRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aditya': typeof AdityaRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aditya' | '/history' | '/insights'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aditya' | '/history' | '/insights'
  id: '__root__' | '/' | '/aditya' | '/history' | '/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdityaRoute: typeof AdityaRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aditya': {
      id: '/aditya'
      path: '/aditya'
      fullPath: '/aditya'
      preLoaderRoute: typeof AdityaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdityaRoute: AdityaRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
